### ISSUE TITLE
Tratamento de dados faltantes

### ISSUE THREAD

**Issue by marfcg** [AlertaDengue/AlertaDengueAnalise#10]
(agora no lugar certo)
O sistema deve ser capaz de lidar com falta de dados ou erro na captura.
Devemos ter uma estrutura que possa reconhecer a "posição/janela temporal" faltante e lidar de acordo.
Sugestão para dados climáticos:
"Buraco simples" (não há apenas o ultimo dado, ou há erro em te, mas há dados em te-1 e te+1): interpolação, quando possível, adotando a escala temporal adequada.
- Se o buraco for na escala horária, interpolar com os dados da série temporal daquele dia.
- Se o buraco for um dia inteiro, ou uma parcela suficientemente grande do día (definir este intervalo limite), interpolar as variáveis de interesse na escala diária. Isto é, pegar a série temporal de temperatura mínima de cada dia e fazer a interpolação nesta escala, por exemplo.
- Semana inteira faltando, ou intervalo suficientemente grande (a definir): repetir dado da semana anterior. Ou fazer interpolação com os dados agregados em escala semanal? Como iremos guardar o dado semanal usado nos relatórios, isso também seria possível.

Embora a sugestão tenha sido feita para dados climáticos, esta estrutura pode ser adaptada para os demais dados.
Importante: o módulo responsável deve reportar o erro e medida adotada, que devem ser registrados no log de execução.

**Comment by claudia-codeco** [comment]
Concordo com a abordagem. Podemos ter uma abordagem diferente para falta do sinan, porem, o que já aconteceu algumas vezes. Nesse caso, temos ausência de dados a semana toda. O que está sendo feito atualmente é usar a tendencia do tweet para estimar os casos. Podemos fazer algo mais elaborado aqui.

**Comment by marfcg** [comment]
Proposta de gerador de estimativas:
https://github.com/marfcg/AlertaDengueAnalise/tree/feature/interpolation/GeraAlerta/fun/funs_marfcg
Script missingdata.py gera estimativas para dados faltantes, a partir da suavização de dados brutos feita pela função existente no script smoothdata.py

**Comment by maxbiostat** [comment]
@marfcg , link ta quebrado.

**Comment by marfcg** [comment]
@maxbiostat obrigado pelo aviso.
Foi movido para pasta própria, para mais clareza na árvore de pastas do projeto.
Segue link correto:
https://github.com/marfcg/AlertaDengueAnalise/tree/feature/interpolation/GeraAlerta/fun/interpolation
